version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "tzlocal"
    update-types: ["version-update:semver-minor", "version-update:semver-patch"]
  open-pull-requests-limit: 10
  commit-message:
    prefix: dep
