version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "tzlocal"
      versions: ["5.x"]
  open-pull-requests-limit: 10
  commit-message:
    prefix: dep
