# https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/

x-common:
  depends_on: &depends-mariadb
    mariadb:
      condition: service_healthy

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    image: discord-bot:local
    container_name: bot
    restart: always
    env_file:
      - config/.env
    depends_on: *depends-mariadb

  bot-dev:
    image: python:3.13-slim
    container_name: bot-dev
    restart: unless-stopped
    working_dir: /app
    depends_on: *depends-mariadb
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python main.py"
    stdin_open: true
    tty: true

  mariadb:
    image: mariadb:12
    hostname: ${MARIADB_HOST}
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 3306:3306
    ulimits:
      memlock:
        soft: 262144
        hard: -1
    volumes:
      - discordbot_mariadb:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    depends_on: *depends-mariadb
    environment:
      - PMA_HOST=${MARIADB_HOST}
      - PMA_USER=${MARIADB_USER}
      - PMA_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - 8080:80

volumes:
  discordbot_mariadb: