[project]
name = "discord-bot"
description = "A Python Discord Bot."
version = "2.1.0b"
readme = { file = ".github/README.md" }
authors = [{ name = "PaulMarisOUMary" }]
license = { file = "LICENSE" }
requires-python = ">=3.10"
dynamic = ["dependencies"]

[project.urls]
Home = "https://github.com/PaulMarisOUMary/Discord-Bot"
Repository = "https://github.com/PaulMarisOUMary/Discord-Bot"
Issues = "https://github.com/PaulMarisOUMary/Discord-Bot"

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }

[tool.ruff]
exclude = [
    ".eggs",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "__pycache__",
    "build",
    "dist",
    "docs",
]
line-length = 88
indent-width = 4

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
ignore = ["Q"]

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
quote-style = "preserve"

[tool.ty.environment]
python-platform = "all"

[tool.ty.analysis]
respect-type-ignore-comments = true